# Generated by Django 6.0.4 on 2026-04-29 06:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("committees", "9999_seed_committee_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resolution_number",
                    models.CharField(
                        blank=True,
                        help_text="Wird automatisch generiert bei Beschlussfassung (Format: YYYYMMDD-XXX)",
                        max_length=20,
                        verbose_name="Beschlussnummer",
                    ),
                ),
                (
                    "proposal",
                    models.TextField(
                        help_text="Der zur Abstimmung gestellte Beschlusstext",
                        verbose_name="Beschlussvorschlag",
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        help_text="Begründung für den Beschlussvorschlag",
                        verbose_name="Begründung",
                    ),
                ),
                (
                    "is_quorate",
                    models.BooleanField(
                        blank=True,
                        help_text="Wird während der Sitzung gesetzt (§ 33 BetrVG)",
                        null=True,
                        verbose_name="Beschlussfähig",
                    ),
                ),
                (
                    "yes_votes",
                    models.PositiveIntegerField(default=0, verbose_name="Ja-Stimmen"),
                ),
                (
                    "no_votes",
                    models.PositiveIntegerField(default=0, verbose_name="Nein-Stimmen"),
                ),
                (
                    "abstentions",
                    models.PositiveIntegerField(default=0, verbose_name="Enthaltungen"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Entwurf"),
                            ("PROPOSED", "Vorgeschlagen"),
                            ("APPROVED", "Beschlossen"),
                            ("REJECTED", "Abgelehnt"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "propose_to_main_committee",
                    models.BooleanField(
                        default=False,
                        help_text="Beschluss kann in TOP des Hauptgremiums aufgenommen werden (§ 28 BetrVG)",
                        verbose_name="Für Hauptgremium vorschlagen",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Zeitpunkt der Beschlussfassung",
                        null=True,
                        verbose_name="Beschlossen/Abgelehnt am",
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolutions",
                        to="committees.committee",
                        verbose_name="Gremium",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_resolutions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beschluss",
                "verbose_name_plural": "Beschlüsse",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["committee", "status"],
                        name="resolutions_committ_78399c_idx",
                    ),
                    models.Index(
                        fields=["status"], name="resolutions_status_67ab3b_idx"
                    ),
                    models.Index(
                        fields=["resolution_number"],
                        name="resolutions_resolut_7b0fba_idx",
                    ),
                ],
                "unique_together": {("committee", "resolution_number")},
            },
        ),
    ]
