# Generated by Django 6.0.4 on 2026-04-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resolutions", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="resolution",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="resolution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resolution_number", ""), _negated=True),
                fields=("committee", "resolution_number"),
                name="unique_resolution_number_per_committee",
            ),
        ),
    ]
