# Generated by Django 6.0.4 on 2026-05-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resolutions", "10000_resolution_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="resolution",
            name="quorum_manually_overridden",
            field=models.BooleanField(
                default=False, verbose_name="Beschlussfähigkeit manuell überschrieben"
            ),
        ),
        migrations.AddField(
            model_name="resolution",
            name="quorum_override_reason",
            field=models.TextField(
                blank=True, verbose_name="Begründung Quorum-Override"
            ),
        ),
    ]
