# Generated by Django 6.0.4 on 2026-05-13 06:52

from django.db import migrations, models


def populate_resolution_descriptions(apps, schema_editor):
    """Preserve legacy proposal and justification text in the new description."""
    Resolution = apps.get_model("resolutions", "Resolution")
    for resolution in Resolution.objects.filter(description="").iterator():
        parts = []
        proposal = (resolution.proposal or "").strip()
        justification = (resolution.justification or "").strip()
        if proposal:
            parts.append(f"Bisheriger Beschlussvorschlag:\n{proposal}")
        if justification:
            parts.append(f"Bisherige Begründung:\n{justification}")
        if parts:
            resolution.description = "\n\n".join(parts)
            resolution.save(update_fields=["description"])


class Migration(migrations.Migration):

    dependencies = [
        ("resolutions", "10002_resolution_decision_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="resolution",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Beschreibung zur Vorbereitung des Beschlussthemas",
                verbose_name="Beschreibung",
            ),
        ),
        migrations.RunPython(
            populate_resolution_descriptions,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="resolution",
            name="justification",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Begründung für den Beschlussvorschlag",
                verbose_name="Begründung",
            ),
        ),
        migrations.AlterField(
            model_name="resolution",
            name="proposal",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Der zur Abstimmung gestellte Beschlusstext",
                verbose_name="Beschlussvorschlag",
            ),
        ),
    ]
