# Generated by Django 6.0.4 on 2026-05-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '10001_resolution_quorum_manually_overridden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='decision_text',
            field=models.TextField(blank=True, help_text='Formatierter Text der tatsächlichen Beschlussfassung in der Sitzung', verbose_name='Beschlussfassung'),
        ),
    ]
