# Generated by Django

from django.db import migrations


def seed_resolution_permissions(apps, schema_editor):
    """Create resolution permissions and assign them to roles."""
    Permission = apps.get_model('roles', 'Permission')
    Role = apps.get_model('roles', 'Role')
    RolePermission = apps.get_model('roles', 'RolePermission')
    
    # ========== STEP 1: Create Permissions ==========
    
    RESOLUTION_PERMISSIONS = [
        ('resolution.create', 'Beschluss erstellen',
         'Neue Beschlussvorschläge erstellen', 'resolution'),
        ('resolution.edit', 'Beschluss bearbeiten',
         'Beschlussvorschläge bearbeiten (vor Aufnahme in TOP)', 'resolution'),
        ('resolution.edit_during_meeting', 'Beschluss während Sitzung bearbeiten',
         'Beschlussvorschläge während laufender Sitzung bearbeiten (nur Vorsitz/Stellv.)', 'resolution'),
        ('resolution.delete', 'Beschluss löschen',
         'Beschlussvorschläge löschen (nur im Status DRAFT)', 'resolution'),
        ('resolution.view', 'Beschluss anzeigen',
         'Beschlussvorschläge und Details ansehen', 'resolution'),
        ('resolution.propose', 'Beschluss vorschlagen',
         'Status auf "Vorgeschlagen" setzen', 'resolution'),
        ('resolution.decide', 'Beschluss beschließen/ablehnen',
         'Status auf "Beschlossen" oder "Abgelehnt" setzen (während Sitzung)', 'resolution'),
    ]
    
    for codename, name, description, category in RESOLUTION_PERMISSIONS:
        Permission.objects.get_or_create(
            codename=codename,
            defaults={
                'name': name,
                'description': description,
                'category': category
            }
        )
    
    # ========== STEP 2: Assign Permissions to Roles ==========
    
    resolution_perms = Permission.objects.filter(category='resolution')
    
    # SYSTEM_ADMIN gets all resolution permissions
    try:
        system_admin = Role.objects.get(codename='SYSTEM_ADMIN')
        for perm in resolution_perms:
            RolePermission.objects.get_or_create(
                role=system_admin,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # CHAIR gets: create, edit, edit_during_meeting, delete, view, propose, decide
    try:
        chair = Role.objects.get(codename='CHAIR')
        chair_perms = resolution_perms.filter(
            codename__in=[
                'resolution.create', 'resolution.edit', 'resolution.edit_during_meeting',
                'resolution.delete', 'resolution.view', 'resolution.propose', 'resolution.decide'
            ]
        )
        for perm in chair_perms:
            RolePermission.objects.get_or_create(
                role=chair,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # VICE_CHAIR gets: create, edit, edit_during_meeting, delete, view, propose, decide
    try:
        vice_chair = Role.objects.get(codename='VICE_CHAIR')
        vice_chair_perms = resolution_perms.filter(
            codename__in=[
                'resolution.create', 'resolution.edit', 'resolution.edit_during_meeting',
                'resolution.delete', 'resolution.view', 'resolution.propose', 'resolution.decide'
            ]
        )
        for perm in vice_chair_perms:
            RolePermission.objects.get_or_create(
                role=vice_chair,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # CLERK gets: create, edit, edit_during_meeting, view, delete, propose
    try:
        clerk = Role.objects.get(codename='CLERK')
        clerk_perms = resolution_perms.filter(
            codename__in=[
                'resolution.create', 'resolution.edit', 'resolution.edit_during_meeting',
                'resolution.view', 'resolution.delete', 'resolution.propose'
            ]
        )
        for perm in clerk_perms:
            RolePermission.objects.get_or_create(
                role=clerk,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # MEMBER gets: create, edit, view, delete, propose
    try:
        member = Role.objects.get(codename='MEMBER')
        member_perms = resolution_perms.filter(
            codename__in=[
                'resolution.create', 'resolution.edit', 'resolution.view',
                'resolution.delete', 'resolution.propose'
            ]
        )
        for perm in member_perms:
            RolePermission.objects.get_or_create(
                role=member,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # SUBSTITUTE, EXTERNAL_MEMBER, GUEST: keine Permissions


def reverse_resolution_permissions(apps, schema_editor):
    """Remove resolution permissions."""
    Permission = apps.get_model('roles', 'Permission')
    RolePermission = apps.get_model('roles', 'RolePermission')
    
    # Delete RolePermissions for resolution permissions
    resolution_perms = Permission.objects.filter(category='resolution')
    RolePermission.objects.filter(permission__in=resolution_perms).delete()
    
    # Delete all resolution permissions
    resolution_perms.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0002_allow_blank_draft_resolution_numbers'),
        ('roles', '9999_seed_roles_and_permissions'),
    ]

    operations = [
        migrations.RunPython(seed_resolution_permissions, reverse_resolution_permissions),
    ]
