# Generated by Django 6.0.4 on 2026-04-25 08:06

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Wird als Login verwendet",
                        max_length=254,
                        unique=True,
                        verbose_name="E-Mail-Adresse",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="Vorname"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Nachname"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Männlich"), ("F", "Weiblich")],
                        help_text="Pflichtangabe für § 15 Abs. 2 BetrVG (Geschlechterquote)",
                        max_length=1,
                        verbose_name="Geschlecht",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Staff-Status"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Beigetreten am"
                    ),
                ),
                (
                    "two_factor_enabled",
                    models.BooleanField(default=False, verbose_name="2FA aktiviert"),
                ),
                (
                    "two_factor_method",
                    models.CharField(
                        blank=True,
                        choices=[("TOTP", "Authenticator App (TOTP)"), ("SMS", "SMS")],
                        max_length=10,
                        verbose_name="2FA-Methode",
                    ),
                ),
                (
                    "totp_secret",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="TOTP-Secret"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benutzer",
                "verbose_name_plural": "Benutzer",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
