# Generated by Django 6.0.4 on 2026-04-25 08:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_twofactorrecoverycode_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="E-Mail-Adresse des einzuladenden Benutzers",
                        max_length=254,
                        verbose_name="E-Mail-Adresse",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Einladungs-Token"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Erstellt am"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Gültig bis")),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Verwendet"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verwendet am"
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eingeladen von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benutzer-Einladung",
                "verbose_name_plural": "Benutzer-Einladungen",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="accounts_us_token_15d7e5_idx"),
                    models.Index(fields=["email"], name="accounts_us_email_d01203_idx"),
                ],
            },
        ),
    ]
