# Generated by Django 6.0.4 on 2026-05-05 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("user_invitation", "Benutzer-Einladung"),
                            ("meeting_invitation", "Sitzungseinladung"),
                        ],
                        max_length=100,
                        unique=True,
                        verbose_name="Vorlagen-Schlüssel",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Betreff")),
                (
                    "body_text",
                    models.TextField(
                        help_text="Platzhalter werden mit {{ platzhalter }} eingefügt.",
                        verbose_name="Text-Inhalt",
                    ),
                ),
                (
                    "body_html",
                    models.TextField(
                        blank=True,
                        help_text="Optionaler HTML-Inhalt. Leer lassen, wenn nur Text versendet werden soll.",
                        verbose_name="HTML-Inhalt",
                    ),
                ),
                (
                    "available_placeholders",
                    models.JSONField(
                        default=list, verbose_name="Verfügbare Platzhalter"
                    ),
                ),
                (
                    "is_system_template",
                    models.BooleanField(
                        default=True,
                        help_text="System-Vorlagen können bearbeitet, aber nicht frei neu angelegt werden.",
                        verbose_name="System-Vorlage",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=100, verbose_name="Sortierung"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
            ],
            options={
                "verbose_name": "E-Mail-Vorlage",
                "verbose_name_plural": "E-Mail-Vorlagen",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
