# Generated by Django 6.0.4 on 2026-05-05

from django.db import migrations


EMAIL_TEMPLATE_PERMISSION = (
    "email_template.edit",
    "E-Mail-Vorlagen bearbeiten",
    "Systemvorgegebene E-Mail-Vorlagen bearbeiten",
    "email_template",
)


EMAIL_TEMPLATE_DEFAULTS = [
    {
        "key": "user_invitation",
        "name": "Benutzer-Einladung",
        "description": "Einladung neuer Benutzer zur Registrierung im BR-Manager.",
        "subject": "Einladung zum BR-Manager",
        "body_text": (
            "Hallo,\n\n"
            "Sie wurden von {{ inviter_name }} zum BR-Manager eingeladen.\n\n"
            "Bitte klicken Sie auf den folgenden Link, um Ihr Konto einzurichten:\n\n"
            "{{ invite_url }}\n\n"
            "Dieser Link ist {{ validity_days }} Tage gültig.\n\n"
            "Mit freundlichen Grüßen\n"
            "Ihr BR-Manager Team\n"
        ),
        "body_html": """
<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
<div style="background-color: #f8f9fa; padding: 20px; border-radius: 5px;">
<h2 style="color: #212529; margin-top: 0;">Einladung zum BR-Manager</h2>
<p>Hallo,</p>
<p>Sie wurden von <strong>{{ inviter_name }}</strong> zum BR-Manager eingeladen.</p>
<p>Bitte klicken Sie auf den folgenden Button, um Ihr Konto einzurichten:</p>
<div style="text-align: center; margin: 30px 0;">
<a href="{{ invite_url }}" style="background-color: #0d6efd; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block; font-weight: bold;">Konto einrichten</a>
</div>
<p style="font-size: 14px; color: #6c757d;">Oder kopieren Sie diesen Link in Ihren Browser:<br><a href="{{ invite_url }}" style="color: #0d6efd; word-break: break-all;">{{ invite_url }}</a></p>
<p style="font-size: 14px; color: #6c757d;"><strong>Hinweis:</strong> Dieser Link ist {{ validity_days }} Tage gültig.</p>
<hr style="border: none; border-top: 1px solid #dee2e6; margin: 20px 0;">
<p style="font-size: 14px; color: #6c757d; margin-bottom: 0;">Mit freundlichen Grüßen<br>Ihr BR-Manager Team</p>
</div>
</body>
</html>""".strip(),
        "available_placeholders": [
            "invite_url",
            "inviter_name",
            "recipient_email",
            "validity_days",
        ],
        "sort_order": 10,
    },
    {
        "key": "meeting_invitation",
        "name": "Sitzungseinladung",
        "description": "Einladung von Teilnehmern zu einer Sitzung inklusive Tagesordnung.",
        "subject": "Einladung: {{ meeting_title }} - {{ meeting_date }}",
        "body_text": (
            "Sehr geehrte/r {{ recipient_name }},\n\n"
            "hiermit laden wir Sie zur Sitzung des {{ committee_name }} ein.\n\n"
            "Titel: {{ meeting_title }}\n"
            "Datum: {{ meeting_date }}\n"
            "Uhrzeit: {{ meeting_start_time }} Uhr\n"
            "Ort: {{ meeting_location }}\n\n"
            "{{ agenda_text }}\n\n"
            "{{ additional_message_block }}\n\n"
            "Mit freundlichen Grüßen\n"
            "BR-Manager"
        ),
        "body_html": "",
        "available_placeholders": [
            "additional_message_block",
            "agenda_text",
            "committee_name",
            "meeting_date",
            "meeting_location",
            "meeting_start_time",
            "meeting_title",
            "message",
            "recipient_email",
            "recipient_name",
        ],
        "sort_order": 20,
    },
]


def seed_email_template_permissions(apps, schema_editor):
    """Create basis templates and assign template edit permissions."""
    EmailTemplate = apps.get_model("email_templates", "EmailTemplate")
    Permission = apps.get_model("roles", "Permission")
    Role = apps.get_model("roles", "Role")
    RolePermission = apps.get_model("roles", "RolePermission")

    for defaults in EMAIL_TEMPLATE_DEFAULTS:
        template, created = EmailTemplate.objects.get_or_create(
            key=defaults["key"],
            defaults={**defaults, "is_system_template": True},
        )
        if created:
            continue

        changed_fields = []
        for field in ["name", "description", "available_placeholders", "sort_order"]:
            if getattr(template, field) != defaults[field]:
                setattr(template, field, defaults[field])
                changed_fields.append(field)
        if not template.is_system_template:
            template.is_system_template = True
            changed_fields.append("is_system_template")
        if changed_fields:
            template.save(update_fields=[*changed_fields, "updated_at"])

    codename, name, description, category = EMAIL_TEMPLATE_PERMISSION
    permission, _created = Permission.objects.get_or_create(
        codename=codename,
        defaults={
            "name": name,
            "description": description,
            "category": category,
        },
    )

    for role_codename in ["SYSTEM_ADMIN", "CHAIR", "VICE_CHAIR"]:
        try:
            role = Role.objects.get(codename=role_codename)
        except Role.DoesNotExist:
            continue
        RolePermission.objects.get_or_create(role=role, permission=permission)


def reverse_email_template_permissions(apps, schema_editor):
    """Remove seeded template permissions and basis templates."""
    EmailTemplate = apps.get_model("email_templates", "EmailTemplate")
    Permission = apps.get_model("roles", "Permission")
    RolePermission = apps.get_model("roles", "RolePermission")

    permission = Permission.objects.filter(codename=EMAIL_TEMPLATE_PERMISSION[0])
    RolePermission.objects.filter(permission__in=permission).delete()
    permission.delete()
    EmailTemplate.objects.filter(
        key__in=[defaults["key"] for defaults in EMAIL_TEMPLATE_DEFAULTS],
        is_system_template=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("email_templates", "0001_initial"),
        ("roles", "9999_seed_roles_and_permissions"),
    ]

    operations = [
        migrations.RunPython(
            seed_email_template_permissions,
            reverse_email_template_permissions,
        ),
    ]
