# Generated by Django 6.0.4 on 2026-05-08 11:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agendas", "10000_resolution_item_permissions"),
        ("meetings", "10000_meeting_current_agenda_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Entwurf"),
                            ("LOCKED", "Gesperrt"),
                            ("FINALIZED", "Finalisiert"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="Protokolltext")),
                (
                    "metadata_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadaten"
                    ),
                ),
                (
                    "attendance_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Anwesenheit"
                    ),
                ),
                (
                    "agenda_snapshot",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Tagesordnung"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "finalized_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finalisiert am"
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finalized_protocols",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Finalisiert von",
                    ),
                ),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol",
                        to="meetings.meeting",
                        verbose_name="Sitzung",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_protocols",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualisiert von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protokoll",
                "verbose_name_plural": "Protokolle",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolAgendaItemNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="Notiz")),
                (
                    "visible_to_loaded_participants",
                    models.BooleanField(
                        default=True, verbose_name="Für geladene Teilnehmer sichtbar"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "agenda_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_notes",
                        to="agendas.agendaitem",
                        verbose_name="Tagesordnungspunkt",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_notes",
                        to="protocols.protocol",
                        verbose_name="Protokoll",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_protocol_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualisiert von",
                    ),
                ),
            ],
            options={
                "verbose_name": "TOP-Protokollnotiz",
                "verbose_name_plural": "TOP-Protokollnotizen",
                "indexes": [
                    models.Index(
                        fields=["protocol", "agenda_item"],
                        name="protocols_p_protoco_b1cd33_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("protocol", "agenda_item"),
                        name="unique_protocol_note_per_item",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProtocolEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("AGENDA", "Tagesordnung"),
                            ("ATTENDANCE", "Anwesenheit"),
                            ("RESOLUTION", "Beschluss"),
                            ("ELECTION", "Wahl"),
                        ],
                        max_length=30,
                        verbose_name="Typ",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Titel")),
                ("content", models.TextField(blank=True, verbose_name="Inhalt")),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="Daten"),
                ),
                (
                    "object_ref",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Objektreferenz"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "agenda_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocol_entries",
                        to="agendas.agendaitem",
                        verbose_name="Tagesordnungspunkt",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="protocols.protocol",
                        verbose_name="Protokoll",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protokolleintrag",
                "verbose_name_plural": "Protokolleinträge",
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["protocol", "entry_type"],
                        name="protocols_p_protoco_67aa71_idx",
                    ),
                    models.Index(
                        fields=["object_ref"], name="protocols_p_object__a781ec_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProtocolRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Geändert am"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(max_length=100, verbose_name="Änderungstyp"),
                ),
                (
                    "object_ref",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Objektreferenz"
                    ),
                ),
                (
                    "old_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Alter Stand"
                    ),
                ),
                (
                    "new_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Neuer Stand"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocol_revisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geändert von",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="protocols.protocol",
                        verbose_name="Protokoll",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protokollrevision",
                "verbose_name_plural": "Protokollrevisionen",
                "ordering": ["-changed_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["protocol", "change_type"],
                        name="protocols_p_protoco_00ddc5_idx",
                    )
                ],
            },
        ),
    ]
