# Generated by Django 6.0.4 on 2026-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendas", "10000_resolution_item_permissions"),
        ("protocols", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="protocolentry",
            constraint=models.UniqueConstraint(
                fields=("protocol", "object_ref"),
                name="unique_protocol_entry_object_ref",
            ),
        ),
    ]
