# Generated by Django 6.0.5 on 2026-05-17 08:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('committee_type', models.CharField(choices=[('MAIN', 'Betriebsrat (Hauptgremium)'), ('COMMITTEE', 'Betriebsausschuss'), ('SUBCOMMITTEE', 'Fachausschuss'), ('GROUP', 'Arbeitsgruppe')], max_length=20, verbose_name='Typ')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcommittees', to='committees.committee', verbose_name='Übergeordnetes Gremium')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Gremium',
                'verbose_name_plural': 'Gremien',
                'ordering': ['committee_type', 'name'],
            },
        ),
    ]
