# Generated by Django 6.0.4 on 2026-04-25 16:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("roles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "committee_type",
                    models.CharField(
                        choices=[
                            ("MAIN", "Betriebsrat (Hauptgremium)"),
                            ("COMMITTEE", "Betriebsausschuss"),
                            ("SUBCOMMITTEE", "Fachausschuss"),
                            ("ADHOC", "Ad-hoc-Ausschuss"),
                        ],
                        max_length=20,
                        verbose_name="Gremiumstyp",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Erstellt am"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gelöscht am"
                    ),
                ),
                (
                    "total_seats",
                    models.PositiveIntegerField(verbose_name="Gesamtanzahl Sitze"),
                ),
                (
                    "quorum_type",
                    models.CharField(
                        choices=[
                            ("SIMPLE_MAJORITY", "Einfache Mehrheit"),
                            ("QUALIFIED", "Qualifizierte Mehrheit"),
                        ],
                        default="SIMPLE_MAJORITY",
                        max_length=20,
                        verbose_name="Quorum-Typ",
                    ),
                ),
                (
                    "personnel_enabled",
                    models.BooleanField(
                        default=False,
                        verbose_name="Personelle Einzelmaßnahmen aktiviert",
                    ),
                ),
                (
                    "substitute_logic_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Nachrücklogik aktiviert"
                    ),
                ),
                (
                    "minority_gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Männlich"), ("F", "Weiblich")],
                        max_length=1,
                        null=True,
                        verbose_name="Minderheitengeschlecht",
                    ),
                ),
                (
                    "minority_min_count",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Mindestanzahl Minderheitengeschlecht",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_committees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gelöscht von",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcommittees",
                        to="committees.committee",
                        verbose_name="Übergeordnetes Gremium",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gremium",
                "verbose_name_plural": "Gremien",
                "ordering": ["committee_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "member_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Reguläres Mitglied"),
                            ("SUBSTITUTE", "Ersatzmitglied"),
                            ("EXTERNAL", "Externes Ausschussmitglied"),
                        ],
                        default="REGULAR",
                        max_length=20,
                        verbose_name="Mitgliedstyp",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Beginn der Mitgliedschaft"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ende der Mitgliedschaft"
                    ),
                ),
                (
                    "election_list_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Listenname bei Listenwahl",
                    ),
                ),
                (
                    "election_list_position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Listenplatz"
                    ),
                ),
                (
                    "election_votes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Stimmenzahl bei Wahl"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gelöscht am"
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="committees.committee",
                        verbose_name="Gremium",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gelöscht von",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="committee_memberships",
                        to="roles.role",
                        verbose_name="Rolle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitgliedschaft",
                "verbose_name_plural": "Mitgliedschaften",
                "ordering": ["committee", "member_type", "-start_date"],
                "unique_together": {("user", "committee")},
            },
        ),
    ]
