# Generated by Django 6.0.4 on 2026-04-26 09:50

from django.db import migrations


def create_committee_permissions(apps, schema_editor):
    """Create standard permissions for committees."""
    Permission = apps.get_model('roles', 'Permission')
    
    # Committee permissions (codename, name, description, category)
    COMMITTEE_PERMISSIONS = [
        ('committee.create', 'Gremium erstellen',
         'Neue Gremien anlegen', 'committee'),
        ('committee.edit', 'Gremium bearbeiten',
         'Existierende Gremien bearbeiten', 'committee'),
        ('committee.view', 'Gremiumsdetails einsehen',
         'Details und Informationen von Gremien anzeigen', 'committee'),
        ('committee.delete', 'Gremium löschen (soft-delete)',
         'Gremien als gelöscht markieren', 'committee'),
        ('committee.manage_members', 'Mitglieder hinzufügen/entfernen/bearbeiten',
         'Mitgliedschaften in Gremien verwalten', 'committee'),
        ('committee.view_members', 'Mitgliederliste einsehen',
         'Liste aller Mitglieder eines Gremiums anzeigen', 'committee'),
    ]
    
    for codename, name, description, category in COMMITTEE_PERMISSIONS:
        Permission.objects.get_or_create(
            codename=codename,
            defaults={
                'name': name,
                'description': description,
                'category': category
            }
        )


def assign_committee_permissions_to_roles(apps, schema_editor):
    """Assign committee permissions to committee roles."""
    Role = apps.get_model('roles', 'Role')
    Permission = apps.get_model('roles', 'Permission')
    RolePermission = apps.get_model('roles', 'RolePermission')
    
    committee_perms = Permission.objects.filter(category='committee')
    
    # SYSTEM_ADMIN gets all committee permissions
    try:
        system_admin = Role.objects.get(codename='SYSTEM_ADMIN')
        for perm in committee_perms:
            RolePermission.objects.get_or_create(
                role=system_admin,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # CHAIR gets all committee permissions
    try:
        chair = Role.objects.get(codename='CHAIR')
        for perm in committee_perms:
            RolePermission.objects.get_or_create(
                role=chair,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # VICE_CHAIR gets all committee permissions
    try:
        vice_chair = Role.objects.get(codename='VICE_CHAIR')
        for perm in committee_perms:
            RolePermission.objects.get_or_create(
                role=vice_chair,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # CLERK gets view and view_members permissions
    try:
        clerk = Role.objects.get(codename='CLERK')
        view_perms = committee_perms.filter(
            codename__in=['committee.view', 'committee.view_members']
        )
        for perm in view_perms:
            RolePermission.objects.get_or_create(
                role=clerk,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # MEMBER gets view and view_members permissions
    try:
        member = Role.objects.get(codename='MEMBER')
        view_perms = committee_perms.filter(
            codename__in=['committee.view', 'committee.view_members']
        )
        for perm in view_perms:
            RolePermission.objects.get_or_create(
                role=member,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # SUBSTITUTE gets view and view_members permissions
    try:
        substitute = Role.objects.get(codename='SUBSTITUTE')
        view_perms = committee_perms.filter(
            codename__in=['committee.view', 'committee.view_members']
        )
        for perm in view_perms:
            RolePermission.objects.get_or_create(
                role=substitute,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # EXTERNAL_MEMBER and GUEST get only view permission
    for role_codename in ['EXTERNAL_MEMBER', 'GUEST']:
        try:
            role = Role.objects.get(codename=role_codename)
            view_perm = committee_perms.filter(codename='committee.view')
            for perm in view_perm:
                RolePermission.objects.get_or_create(
                    role=role,
                    permission=perm
                )
        except Role.DoesNotExist:
            pass


def reverse_committee_permissions(apps, schema_editor):
    """Remove created committee permissions."""
    Permission = apps.get_model('roles', 'Permission')
    
    # Delete all committee permissions created by this migration
    Permission.objects.filter(
        codename__in=[
            'committee.create', 'committee.edit', 'committee.view',
            'committee.delete', 'committee.manage_members', 'committee.view_members'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_alter_membership_role'),
        ('roles', '0004_seed_roles'),  # Requires roles to exist
    ]

    operations = [
        migrations.RunPython(create_committee_permissions, reverse_committee_permissions),
        migrations.RunPython(assign_committee_permissions_to_roles, migrations.RunPython.noop),
    ]
