# Generated by Django 6.0.4 on 2026-04-29 06:24

from django.db import migrations, models


def set_betriebsausschuss_can_create_resolutions(apps, schema_editor):
    """Set can_create_resolutions=True for all COMMITTEE types."""
    Committee = apps.get_model('committees', 'Committee')
    Committee.objects.filter(committee_type='COMMITTEE').update(can_create_resolutions=True)


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "9999_seed_committee_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="committee",
            name="can_create_resolutions",
            field=models.BooleanField(
                default=False,
                help_text="Erlaubt diesem Gremium Beschlüsse zu erstellen (Betriebsausschuss automatisch)",
                verbose_name="Beschlüsse erstellen erlauben",
            ),
        ),
        migrations.RunPython(
            set_betriebsausschuss_can_create_resolutions,
            reverse_code=migrations.RunPython.noop
        ),
    ]
