# Generated by Django 6.0.4 on 2026-04-26 10:02

from django.db import migrations


def add_view_all_permission(apps, schema_editor):
    """Add 'view_all' permission for viewing all committees regardless of membership."""
    Permission = apps.get_model('roles', 'Permission')
    Role = apps.get_model('roles', 'Role')
    RolePermission = apps.get_model('roles', 'RolePermission')
    
    # Create the new permission
    view_all_perm, created = Permission.objects.get_or_create(
        codename='committee.view_all',
        defaults={
            'name': 'Alle Gremien einsehen',
            'description': 'Alle Gremien unabhängig von eigener Mitgliedschaft einsehen',
            'category': 'committee'
        }
    )
    
    # Assign to SYSTEM_ADMIN
    try:
        system_admin = Role.objects.get(codename='SYSTEM_ADMIN')
        RolePermission.objects.get_or_create(
            role=system_admin,
            permission=view_all_perm
        )
    except Role.DoesNotExist:
        pass


def reverse_view_all_permission(apps, schema_editor):
    """Remove 'view_all' permission."""
    Permission = apps.get_model('roles', 'Permission')
    
    Permission.objects.filter(codename='committee.view_all').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_seed_committee_permissions'),
        ('roles', '0004_seed_roles'),
    ]

    operations = [
        migrations.RunPython(add_view_all_permission, reverse_view_all_permission),
    ]
