# Generated by Django 6.0.4 on 2026-04-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_add_view_all_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='auto_composition_enabled',
            field=models.BooleanField(default=False, help_text='Vorsitzende und Mitglieder mit auto_include_in_ba werden automatisch hinzugefügt (nur für Betriebsausschuss)', verbose_name='Automatische Zusammensetzung'),
        ),
        migrations.AddField(
            model_name='committee',
            name='delegated_tasks',
            field=models.TextField(blank=True, help_text='Vom Betriebsrat delegierte Aufgaben zur selbständigen Erledigung (§ 27 Abs. 2 BetrVG)', verbose_name='Delegierte Aufgaben'),
        ),
    ]
