# Generated by Django 6.0.4 on 2026-04-27 20:45

from django.db import migrations


def seed_committee_permissions(apps, schema_editor):
    """Create committee permissions and assign them to roles."""
    Permission = apps.get_model('roles', 'Permission')
    Role = apps.get_model('roles', 'Role')
    RolePermission = apps.get_model('roles', 'RolePermission')
    
    # ========== STEP 1: Create Permissions ==========
    
    # Committee permissions (codename, name, description, category)
    COMMITTEE_PERMISSIONS = [
        ('committee.create', 'Gremium erstellen',
         'Neue Gremien anlegen', 'committee'),
        ('committee.edit', 'Gremium bearbeiten',
         'Existierende Gremien bearbeiten', 'committee'),
        ('committee.view', 'Gremiumsdetails einsehen',
         'Details und Informationen von Gremien anzeigen', 'committee'),
        ('committee.view_all', 'Alle Gremien einsehen',
         'Alle Gremien unabhängig von eigener Mitgliedschaft einsehen', 'committee'),
        ('committee.delete', 'Gremium löschen (soft-delete)',
         'Gremien als gelöscht markieren', 'committee'),
        ('committee.manage_members', 'Mitglieder hinzufügen/entfernen/bearbeiten',
         'Mitgliedschaften in Gremien verwalten', 'committee'),
        ('committee.view_members', 'Mitgliederliste einsehen',
         'Liste aller Mitglieder eines Gremiums anzeigen', 'committee'),
    ]
    
    for codename, name, description, category in COMMITTEE_PERMISSIONS:
        Permission.objects.get_or_create(
            codename=codename,
            defaults={
                'name': name,
                'description': description,
                'category': category
            }
        )
    
    # ========== STEP 2: Assign Permissions to Roles ==========
    
    committee_perms = Permission.objects.filter(category='committee')
    
    # SYSTEM_ADMIN gets all committee permissions
    try:
        system_admin = Role.objects.get(codename='SYSTEM_ADMIN')
        for perm in committee_perms:
            RolePermission.objects.get_or_create(
                role=system_admin,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # CHAIR gets: create, edit, view, delete, manage_members, view_members
    try:
        chair = Role.objects.get(codename='CHAIR')
        chair_perms = committee_perms.filter(
            codename__in=[
                'committee.create', 'committee.edit', 'committee.view',
                'committee.delete', 'committee.manage_members', 'committee.view_members'
            ]
        )
        for perm in chair_perms:
            RolePermission.objects.get_or_create(
                role=chair,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # VICE_CHAIR gets: create, edit, view, delete, manage_members, view_members
    try:
        vice_chair = Role.objects.get(codename='VICE_CHAIR')
        vice_chair_perms = committee_perms.filter(
            codename__in=[
                'committee.create', 'committee.edit', 'committee.view',
                'committee.delete', 'committee.manage_members', 'committee.view_members'
            ]
        )
        for perm in vice_chair_perms:
            RolePermission.objects.get_or_create(
                role=vice_chair,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # CLERK gets: view, view_members
    try:
        clerk = Role.objects.get(codename='CLERK')
        clerk_perms = committee_perms.filter(
            codename__in=['committee.view', 'committee.view_members']
        )
        for perm in clerk_perms:
            RolePermission.objects.get_or_create(
                role=clerk,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # MEMBER gets: view, view_members
    try:
        member = Role.objects.get(codename='MEMBER')
        member_perms = committee_perms.filter(
            codename__in=['committee.view', 'committee.view_members']
        )
        for perm in member_perms:
            RolePermission.objects.get_or_create(
                role=member,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # SUBSTITUTE gets: view, view_members
    try:
        substitute = Role.objects.get(codename='SUBSTITUTE')
        substitute_perms = committee_perms.filter(
            codename__in=['committee.view', 'committee.view_members']
        )
        for perm in substitute_perms:
            RolePermission.objects.get_or_create(
                role=substitute,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # EXTERNAL_MEMBER gets: view, view_members
    try:
        external_member = Role.objects.get(codename='EXTERNAL_MEMBER')
        external_perms = committee_perms.filter(
            codename__in=['committee.view', 'committee.view_members']
        )
        for perm in external_perms:
            RolePermission.objects.get_or_create(
                role=external_member,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # GUEST gets: view, view_members
    try:
        guest = Role.objects.get(codename='GUEST')
        guest_perms = committee_perms.filter(
            codename__in=['committee.view', 'committee.view_members']
        )
        for perm in guest_perms:
            RolePermission.objects.get_or_create(
                role=guest,
                permission=perm
            )
    except Role.DoesNotExist:
        pass


def reverse_committee_permissions(apps, schema_editor):
    """Remove committee permissions."""
    Permission = apps.get_model('roles', 'Permission')
    RolePermission = apps.get_model('roles', 'RolePermission')
    
    # Delete RolePermissions for committee permissions
    committee_perms = Permission.objects.filter(category='committee')
    RolePermission.objects.filter(permission__in=committee_perms).delete()
    
    # Delete all committee permissions
    committee_perms.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_add_betriebsausschuss_fields'),
        ('roles', '9999_seed_roles_and_permissions'),  # Requires roles to exist
    ]

    operations = [
        migrations.RunPython(seed_committee_permissions, reverse_committee_permissions),
    ]
