# Generated by Django 6.0.4 on 2026-04-27 20:45

from django.db import migrations


def seed_committee_permissions(apps, schema_editor):
    """Create committee permissions and assign them to roles."""
    Permission = apps.get_model('roles', 'Permission')
    Role = apps.get_model('roles', 'Role')
    RolePermission = apps.get_model('roles', 'RolePermission')
    
    # ========== STEP 1: Create Permissions ==========
    
    # Committee permissions (codename, name, description, category)
    COMMITTEE_PERMISSIONS = [
        ('committee.create', 'Gremium erstellen',
         'Neue Gremien anlegen', 'committee'),
        ('committee.edit', 'Gremium bearbeiten',
         'Existierende Gremien bearbeiten', 'committee'),
        ('committee.view', 'Gremiumsdetails einsehen',
         'Details und Informationen von Gremien anzeigen', 'committee'),
        ('committee.view_all', 'Alle Gremien einsehen',
         'Alle Gremien unabhängig von eigener Mitgliedschaft einsehen', 'committee'),
        ('committee.delete', 'Gremium löschen (soft-delete)',
         'Gremien als gelöscht markieren', 'committee'),
        ('committee.manage_members', 'Mitglieder hinzufügen/entfernen/bearbeiten',
         'Mitgliedschaften in Gremien verwalten', 'committee'),
        ('committee.view_members', 'Mitgliederliste einsehen',
         'Liste aller Mitglieder eines Gremiums anzeigen', 'committee'),
    ]
    
    for codename, name, description, category in COMMITTEE_PERMISSIONS:
        Permission.objects.get_or_create(
            codename=codename,
            defaults={
                'name': name,
                'description': description,
                'category': category
            }
        )
    
    # ========== STEP 2: Assign Permissions to Roles ==========
    
    committee_perms = Permission.objects.filter(category='committee')
    
    # SYSTEM_ADMIN gets all committee permissions
    try:
        system_admin = Role.objects.get(codename='SYSTEM_ADMIN')
        for perm in committee_perms:
            RolePermission.objects.get_or_create(
                role=system_admin,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # CHAIR gets all committee permissions
    try:
        chair = Role.objects.get(codename='CHAIR')
        for perm in committee_perms:
            RolePermission.objects.get_or_create(
                role=chair,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # VICE_CHAIR gets all committee permissions
    try:
        vice_chair = Role.objects.get(codename='VICE_CHAIR')
        for perm in committee_perms:
            RolePermission.objects.get_or_create(
                role=vice_chair,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # CLERK gets view and view_members permissions
    try:
        clerk = Role.objects.get(codename='CLERK')
        view_perms = committee_perms.filter(
            codename__in=['committee.view', 'committee.view_members']
        )
        for perm in view_perms:
            RolePermission.objects.get_or_create(
                role=clerk,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # MEMBER gets view and view_members permissions
    try:
        member = Role.objects.get(codename='MEMBER')
        view_perms = committee_perms.filter(
            codename__in=['committee.view', 'committee.view_members']
        )
        for perm in view_perms:
            RolePermission.objects.get_or_create(
                role=member,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # SUBSTITUTE gets view and view_members permissions
    try:
        substitute = Role.objects.get(codename='SUBSTITUTE')
        view_perms = committee_perms.filter(
            codename__in=['committee.view', 'committee.view_members']
        )
        for perm in view_perms:
            RolePermission.objects.get_or_create(
                role=substitute,
                permission=perm
            )
    except Role.DoesNotExist:
        pass
    
    # EXTERNAL_MEMBER and GUEST get only view permission
    for role_codename in ['EXTERNAL_MEMBER', 'GUEST']:
        try:
            role = Role.objects.get(codename=role_codename)
            view_perm = committee_perms.filter(codename='committee.view')
            for perm in view_perm:
                RolePermission.objects.get_or_create(
                    role=role,
                    permission=perm
                )
        except Role.DoesNotExist:
            pass


def reverse_committee_permissions(apps, schema_editor):
    """Remove committee permissions."""
    Permission = apps.get_model('roles', 'Permission')
    RolePermission = apps.get_model('roles', 'RolePermission')
    
    # Delete RolePermissions for committee permissions
    committee_perms = Permission.objects.filter(category='committee')
    RolePermission.objects.filter(permission__in=committee_perms).delete()
    
    # Delete all committee permissions
    committee_perms.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_add_betriebsausschuss_fields'),
        ('roles', '9999_seed_roles_and_permissions'),  # Requires roles to exist
    ]

    operations = [
        migrations.RunPython(seed_committee_permissions, reverse_committee_permissions),
    ]
