# Generated by Django

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendas', '0004_add_resolution_item_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_number', models.CharField(editable=False, help_text='Wird automatisch berechnet', max_length=20, verbose_name='TOP-Nummer')),
                ('title', models.CharField(max_length=500, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('sort_order', models.FloatField(default=0.0, verbose_name='Sortierung')),
                ('item_type', models.CharField(editable=False, max_length=50, verbose_name='Typ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('election_type', models.CharField(choices=[('PERSON', 'Personenwahl')], default='PERSON', help_text='Derzeit wird nur die Personenwahl unterstützt', max_length=20, verbose_name='Wahlart')),
                ('majority_type', models.CharField(choices=[('absolute', 'Absolute Mehrheit'), ('relative', 'Relative Mehrheit')], default='absolute', help_text='Absolute oder relative Mehrheit für die vorbereitete Wahl', max_length=20, verbose_name='Mehrheitserfordernis')),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('PUBLISHED', 'Veröffentlicht')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='agendas.agenda', verbose_name='Tagesordnung')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='elections.election', verbose_name='Übergeordneter TOP')),
            ],
            options={
                'verbose_name': 'Wahl',
                'verbose_name_plural': 'Wahlen',
                'ordering': ['agenda', 'sort_order'],
                'indexes': [models.Index(fields=['agenda', 'status'], name='elections_e_agenda__46a051_idx'), models.Index(fields=['status'], name='elections_e_status_e3ccd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Freitextname der kandidierenden Person; keine Benutzer-Verknüpfung', max_length=255, verbose_name='Name')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election', verbose_name='Wahl')),
            ],
            options={
                'verbose_name': 'Kandidierende Person',
                'verbose_name_plural': 'Kandidierende Personen',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('election', 'name'), name='unique_candidate_name_per_election')],
            },
        ),
    ]
