# Generated by Django 6.0.4 on 2026-04-29 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agendas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "election_type",
                    models.CharField(
                        choices=[("PERSON", "Personenwahl")],
                        default="PERSON",
                        help_text="Derzeit wird nur die Personenwahl unterstützt",
                        max_length=20,
                        verbose_name="Wahlart",
                    ),
                ),
                (
                    "majority_type",
                    models.CharField(
                        choices=[
                            ("absolute", "Absolute Mehrheit"),
                            ("relative", "Relative Mehrheit"),
                        ],
                        default="absolute",
                        help_text="Absolute oder relative Mehrheit für die vorbereitete Wahl",
                        max_length=20,
                        verbose_name="Mehrheitserfordernis",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Entwurf"), ("PUBLISHED", "Veröffentlicht")],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "agenda_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="election_link",
                        to="agendas.agendaitem",
                        verbose_name="Tagesordnungspunkt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wahl",
                "verbose_name_plural": "Wahlen",
                "ordering": ["agenda_item__agenda", "agenda_item__sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ElectionCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Freitextname der kandidierenden Person; keine Benutzer-Verknüpfung",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sortierung"),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="elections.election",
                        verbose_name="Wahl",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kandidierende Person",
                "verbose_name_plural": "Kandidierende Personen",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="election",
            index=models.Index(fields=["status"], name="elections_e_status_e3ccd0_idx"),
        ),
        migrations.AddConstraint(
            model_name="electioncandidate",
            constraint=models.UniqueConstraint(
                fields=("election", "name"), name="unique_candidate_name_per_election"
            ),
        ),
    ]
