# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_add_resolution_item_permission'),
        ('elections', '9999_seed_election_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='parent_regular',
            field=models.ForeignKey(
                blank=True,
                help_text='Ermöglicht Wahlen als Unter-TOP regulärer Tagesordnungspunkte',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='election_children',
                to='agendas.agendaitemregular',
                verbose_name='Übergeordneter regulärer TOP',
            ),
        ),
    ]
