# Generated by Django 6.0.4 on 2026-05-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "10000_electionresult_electioncandidateresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Entwurf"),
                    ("PUBLISHED", "Veröffentlicht"),
                    ("COMPLETED", "Durchgeführt"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
