# Generated by Django 6.0.4 on 2026-05-08 11:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "9999_seed_election_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_quorate",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Beschlussfähig"
                    ),
                ),
                (
                    "quorum_manually_overridden",
                    models.BooleanField(
                        default=False,
                        verbose_name="Beschlussfähigkeit manuell überschrieben",
                    ),
                ),
                (
                    "quorum_override_reason",
                    models.TextField(
                        blank=True, verbose_name="Begründung Quorum-Override"
                    ),
                ),
                (
                    "eligible_voters",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Stimmberechtigte"
                    ),
                ),
                (
                    "votes_cast",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Abgegebene Stimmen"
                    ),
                ),
                (
                    "invalid_votes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ungültige Stimmen"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Erfasst am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "election",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="elections.election",
                        verbose_name="Wahl",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_election_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erfasst von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wahlergebnis",
                "verbose_name_plural": "Wahlergebnisse",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="ElectionCandidateResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "votes",
                    models.PositiveIntegerField(default=0, verbose_name="Stimmen"),
                ),
                ("elected", models.BooleanField(default=False, verbose_name="Gewählt")),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="elections.electioncandidate",
                        verbose_name="Kandidierende Person",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_results",
                        to="elections.electionresult",
                        verbose_name="Wahlergebnis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kandidierenden-Ergebnis",
                "verbose_name_plural": "Kandidierenden-Ergebnisse",
                "ordering": ["candidate__sort_order", "candidate__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("result", "candidate"),
                        name="unique_candidate_result_per_election_result",
                    )
                ],
            },
        ),
    ]
