# Generated by Django

from django.db import migrations


def seed_election_permissions(apps, schema_editor):
    """Create election permissions and assign them to roles."""
    Permission = apps.get_model('roles', 'Permission')
    Role = apps.get_model('roles', 'Role')
    RolePermission = apps.get_model('roles', 'RolePermission')

    election_permissions = [
        ('election.create', 'Wahl erstellen', 'Wahlen als Tagesordnungspunkt vorbereiten', 'election'),
        ('election.view', 'Wahl anzeigen', 'Vorbereitete Wahldaten ansehen', 'election'),
        ('election.edit', 'Wahl bearbeiten', 'Wahldaten im Entwurf bearbeiten und veröffentlichen', 'election'),
        ('election.delete', 'Wahl löschen', 'Wahl-TOPs im Entwurf löschen', 'election'),
    ]

    for codename, name, description, category in election_permissions:
        Permission.objects.get_or_create(
            codename=codename,
            defaults={
                'name': name,
                'description': description,
                'category': category,
            }
        )

    role_permissions = {
        'SYSTEM_ADMIN': [permission[0] for permission in election_permissions],
        'CHAIR': ['election.create', 'election.view', 'election.edit', 'election.delete'],
        'VICE_CHAIR': ['election.create', 'election.view', 'election.edit', 'election.delete'],
        'CLERK': ['election.create', 'election.view', 'election.edit', 'election.delete'],
        'MEMBER': ['election.view'],
    }

    for role_codename, permission_codenames in role_permissions.items():
        try:
            role = Role.objects.get(codename=role_codename)
        except Role.DoesNotExist:
            continue

        permissions = Permission.objects.filter(codename__in=permission_codenames)
        for permission in permissions:
            RolePermission.objects.get_or_create(role=role, permission=permission)


def reverse_election_permissions(apps, schema_editor):
    """Remove election permissions."""
    Permission = apps.get_model('roles', 'Permission')
    RolePermission = apps.get_model('roles', 'RolePermission')

    election_permissions = Permission.objects.filter(category='election')
    RolePermission.objects.filter(permission__in=election_permissions).delete()
    election_permissions.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        ('roles', '9999_seed_roles_and_permissions'),
    ]

    operations = [
        migrations.RunPython(seed_election_permissions, reverse_election_permissions),
    ]
