# Generated by Django 6.0.4 on 2026-04-28 09:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meetings", "9999_seed_meeting_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agenda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda",
                        to="meetings.meeting",
                        verbose_name="Sitzung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tagesordnung",
                "verbose_name_plural": "Tagesordnungen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgendaItemRegular",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_number",
                    models.CharField(
                        editable=False,
                        help_text="Wird automatisch berechnet",
                        max_length=20,
                        verbose_name="TOP-Nummer",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Titel")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "sort_order",
                    models.FloatField(default=0.0, verbose_name="Sortierung"),
                ),
                (
                    "item_type",
                    models.CharField(editable=False, max_length=50, verbose_name="Typ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "agenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="agendas.agenda",
                        verbose_name="Tagesordnung",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="agendas.agendaitemregular",
                        verbose_name="Übergeordneter TOP",
                    ),
                ),
            ],
            options={
                "verbose_name": "Normaler TOP",
                "verbose_name_plural": "Normale TOPs",
                "ordering": ["sort_order", "item_number"],
            },
        ),
    ]
