# Generated by Django 6.0.4 on 2026-04-29 19:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meetings", "9999_seed_meeting_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agenda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda",
                        to="meetings.meeting",
                        verbose_name="Sitzung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tagesordnung",
                "verbose_name_plural": "Tagesordnungen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgendaItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_number",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Wird automatisch berechnet",
                        max_length=20,
                        verbose_name="TOP-Nummer",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Titel")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "sort_order",
                    models.FloatField(default=0.0, verbose_name="Sortierung"),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Normaler TOP"),
                            ("RESOLUTION", "Beschluss"),
                            ("ELECTION", "Wahl"),
                        ],
                        default="REGULAR",
                        max_length=20,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "agenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="agendas.agenda",
                        verbose_name="Tagesordnung",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="agendas.agendaitem",
                        verbose_name="Übergeordneter TOP",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tagesordnungspunkt",
                "verbose_name_plural": "Tagesordnungspunkte",
                "ordering": ["agenda", "sort_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["agenda", "item_type"],
                        name="agendas_age_agenda__abc35e_idx",
                    ),
                    models.Index(
                        fields=["agenda", "parent"],
                        name="agendas_age_agenda__24137e_idx",
                    ),
                ],
            },
        ),
    ]
