# Generated by Django 6.0.4 on 2026-05-01 06:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("committees", "0004_committee_can_create_resolutions"),
        ("meetings", "9999_seed_meeting_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Snapshot-Adresse für interne und externe Empfänger",
                        max_length=254,
                        verbose_name="E-Mail-Adresse",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=250, verbose_name="Anzeigename"),
                ),
                (
                    "participant_type",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "Interner Teilnehmer"),
                            ("EXTERNAL", "Externer Teilnehmer"),
                            ("SUBSTITUTE", "Nachgerückter Ersatz"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                        verbose_name="Teilnehmerart",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Eingeplant"),
                            ("INVITED", "Eingeladen"),
                            ("ABSENT", "Abwesend"),
                            ("SUBSTITUTE_PROPOSED", "Ersatz vorgeschlagen"),
                            ("REPLACED", "Ersetzt"),
                            ("REPLACEMENT", "Ersatz bestätigt"),
                            ("CANCELLED", "Entfernt"),
                        ],
                        default="CREATED",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "absence_reason",
                    models.TextField(blank=True, verbose_name="Abwesenheitsgrund"),
                ),
                (
                    "nachladefaehig",
                    models.BooleanField(
                        default=True,
                        help_text="Wenn aktiv, wird ein Ersatzvorschlag ermittelt.",
                        verbose_name="Nachladefähig",
                    ),
                ),
                (
                    "is_initially_invited",
                    models.BooleanField(
                        default=True, verbose_name="Initial eingeladen"
                    ),
                ),
                (
                    "invite_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Einladung versendet am"
                    ),
                ),
                (
                    "last_notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zuletzt benachrichtigt am"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="meetings.meeting",
                        verbose_name="Sitzung",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_participants",
                        to="committees.membership",
                        verbose_name="Mitgliedschaft",
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaced_participants",
                        to="participants.meetingparticipant",
                        verbose_name="Ersetzt durch",
                    ),
                ),
                (
                    "replaces",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_participants",
                        to="participants.meetingparticipant",
                        verbose_name="Ersetzt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sitzungsteilnehmer",
                "verbose_name_plural": "Sitzungsteilnehmer",
                "ordering": ["meeting", "participant_type", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="MeetingParticipantChangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Geändert am"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Eingeplant"),
                            ("INVITED", "Eingeladen"),
                            ("ABSENCE_MARKED", "Abwesend gesetzt"),
                            ("SUBSTITUTE_PROPOSED", "Ersatz vorgeschlagen"),
                            ("SUBSTITUTE_CONFIRMED", "Ersatz bestätigt"),
                            ("REPLACED", "Ersetzt"),
                            ("CANCELLED", "Entfernt"),
                            ("REACTIVATED", "Reaktiviert / angepasst"),
                        ],
                        max_length=40,
                        verbose_name="Aktion",
                    ),
                ),
                (
                    "old_state",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Alter Zustand"
                    ),
                ),
                (
                    "new_state",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Neuer Zustand"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Notiz")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participant_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geändert von",
                    ),
                ),
                (
                    "meeting_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="participants.meetingparticipant",
                        verbose_name="Sitzungsteilnehmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teilnehmer-Änderung",
                "verbose_name_plural": "Teilnehmer-Änderungen",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="meetingparticipant",
            index=models.Index(
                fields=["meeting", "status"], name="participant_meeting_8a5ae5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingparticipant",
            index=models.Index(fields=["email"], name="participant_email_322e5b_idx"),
        ),
        migrations.AddConstraint(
            model_name="meetingparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("membership__isnull", False)),
                fields=("meeting", "membership"),
                name="unique_meeting_participant_membership",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingparticipantchangelog",
            index=models.Index(
                fields=["meeting_participant", "changed_at"],
                name="participant_meeting_7d4272_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingparticipantchangelog",
            index=models.Index(fields=["action"], name="participant_action_f3ab8c_idx"),
        ),
    ]
