# Generated by Django 6.0.4 on 2026-05-08 11:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0004_committee_can_create_resolutions"),
        ("meetings", "10000_meeting_current_agenda_item"),
        ("participants", "10001_single_row_substitutes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingAttendanceEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CONFIRMED_PRESENT", "Anwesenheit bestätigt"),
                            ("RECONFIRMED", "Sitzung erneut bestätigt"),
                            ("LEFT", "Abwesend gemeldet"),
                            ("RETURNED", "Zurückgemeldet"),
                            ("MARKED_ABSENT", "Abwesend markiert"),
                        ],
                        max_length=40,
                        verbose_name="Ereignis",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Zeitpunkt"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("SELF", "Selbst"),
                            ("TOTP", "TOTP"),
                            ("RECOVERY", "Recovery-Code"),
                            ("SYSTEM", "System"),
                        ],
                        default="SELF",
                        max_length=20,
                        verbose_name="Methode",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadaten"
                    ),
                ),
            ],
            options={
                "verbose_name": "Anwesenheitsereignis",
                "verbose_name_plural": "Anwesenheitsereignisse",
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="meetingparticipant",
            name="attendance_status",
            field=models.CharField(
                choices=[
                    ("NOT_CONFIRMED", "Nicht bestätigt"),
                    ("PRESENT", "Anwesend"),
                    ("LEFT", "Abwesend während der Sitzung"),
                    ("ABSENT", "Abwesend"),
                ],
                default="NOT_CONFIRMED",
                max_length=30,
                verbose_name="Anwesenheitsstatus",
            ),
        ),
        migrations.AddField(
            model_name="meetingparticipant",
            name="last_attendance_event_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Letzte Anwesenheitsänderung"
            ),
        ),
        migrations.AddField(
            model_name="meetingparticipant",
            name="last_self_confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Zuletzt selbst bestätigt"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingparticipant",
            index=models.Index(
                fields=["meeting", "attendance_status"],
                name="participant_meeting_8192e3_idx",
            ),
        ),
        migrations.AddField(
            model_name="meetingattendanceevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meeting_attendance_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Akteur",
            ),
        ),
        migrations.AddField(
            model_name="meetingattendanceevent",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_events",
                to="meetings.meeting",
                verbose_name="Sitzung",
            ),
        ),
        migrations.AddField(
            model_name="meetingattendanceevent",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_events",
                to="participants.meetingparticipant",
                verbose_name="Teilnehmer",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingattendanceevent",
            index=models.Index(
                fields=["meeting", "occurred_at"], name="participant_meeting_40cb7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingattendanceevent",
            index=models.Index(
                fields=["participant", "event_type"],
                name="participant_partici_d0174c_idx",
            ),
        ),
    ]
