# Generated by Django 6.0.4 on 2026-05-13 06:52

from django.db import migrations, models


def mark_legacy_attendance_events(apps, schema_editor):
    """
    Mark pre-migration presence events without written confirmation as legacy.

    This preserves the historical attendance record while clearly distinguishing
    events that occurred before the written confirmation requirement was introduced.
    Legacy events will still appear in attendance timelines but are flagged as
    pre-requirement events for audit/legal clarity.
    """
    MeetingAttendanceEvent = apps.get_model("participants", "MeetingAttendanceEvent")

    # Find all presence-opening events without written confirmation
    legacy_events = MeetingAttendanceEvent.objects.filter(
        event_type__in=["CONFIRMED_PRESENT", "RECONFIRMED", "RETURNED"],
        written_confirmation="",
    )

    # Mark them as legacy in metadata for audit trail
    for event in legacy_events:
        if not event.metadata:
            event.metadata = {}
        event.metadata["legacy_pre_written_confirmation"] = True

    # Bulk update
    MeetingAttendanceEvent.objects.bulk_update(legacy_events, ["metadata"])


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "10002_meetingattendanceevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingattendanceevent",
            name="written_confirmation",
            field=models.TextField(
                blank=True,
                help_text="Vom Teilnehmer eingegebene Erklärung zur persönlichen Anwesenheit.",
                verbose_name="Schriftliche Anwesenheitsbestätigung",
            ),
        ),
        migrations.AddField(
            model_name="meetingparticipant",
            name="last_written_confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Zuletzt schriftlich bestätigt"
            ),
        ),
        migrations.RunPython(
            mark_legacy_attendance_events,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
