# Generated by Django 6.0.4 on 2026-05-01

import django.db.models.deletion
from django.db import migrations, models


def delete_participants_without_membership(apps, schema_editor):
    """Remove invalid participant rows that cannot be represented anymore."""
    meeting_participant = apps.get_model("participants", "MeetingParticipant")
    meeting_participant.objects.filter(membership__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("participants", "9999_seed_participant_permissions"),
    ]

    operations = [
        migrations.RunPython(
            delete_participants_without_membership,
            migrations.RunPython.noop,
        ),
        migrations.RemoveIndex(
            model_name="meetingparticipant",
            name="participant_email_322e5b_idx",
        ),
        migrations.RemoveConstraint(
            model_name="meetingparticipant",
            name="unique_meeting_participant_membership",
        ),
        migrations.RemoveField(
            model_name="meetingparticipant",
            name="user",
        ),
        migrations.RemoveField(
            model_name="meetingparticipant",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="meetingparticipant",
            name="email",
        ),
        migrations.AlterField(
            model_name="meetingparticipant",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meeting_participants",
                to="committees.membership",
                verbose_name="Mitgliedschaft",
            ),
        ),
        migrations.AlterModelOptions(
            name="meetingparticipant",
            options={
                "ordering": [
                    "meeting",
                    "participant_type",
                    "membership__user__last_name",
                    "membership__user__first_name",
                ],
                "verbose_name": "Sitzungsteilnehmer",
                "verbose_name_plural": "Sitzungsteilnehmer",
            },
        ),
        migrations.AddConstraint(
            model_name="meetingparticipant",
            constraint=models.UniqueConstraint(
                fields=("meeting", "membership"),
                name="unique_meeting_participant_membership",
            ),
        ),
    ]
