# Generated by OpenCode on 2026-05-01

import django.db.models.deletion
from django.db import migrations, models


def move_replacements_to_participant_rows(apps, schema_editor):
    """Store selected replacements on the absent participant row and drop extra rows."""
    meeting_participant = apps.get_model("participants", "MeetingParticipant")

    for participant in meeting_participant.objects.filter(replaced_by__isnull=False):
        replacement = participant.replaced_by
        if replacement and replacement.membership_id:
            participant.substitute_membership_id = replacement.membership_id
            participant.status = "ABSENT"
            participant.nachladefaehig = True
            participant.save(update_fields=[
                "substitute_membership",
                "status",
                "nachladefaehig",
                "updated_at",
            ])

    meeting_participant.objects.filter(replaces__isnull=False).delete()
    meeting_participant.objects.filter(status="REPLACEMENT").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("participants", "10000_simplify_participant_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingparticipant",
            name="substitute_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meeting_substitutions",
                to="committees.membership",
                verbose_name="Nachgeladenes Ersatzmitglied",
            ),
        ),
        migrations.RunPython(
            move_replacements_to_participant_rows,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="meetingparticipant",
            name="replaced_by",
        ),
        migrations.RemoveField(
            model_name="meetingparticipant",
            name="replaces",
        ),
        migrations.AlterField(
            model_name="meetingparticipant",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Eingeplant"),
                    ("INVITED", "Eingeladen"),
                    ("ABSENT", "Abwesend"),
                    ("SUBSTITUTE_PROPOSED", "Abwesend, Ersatz vorgeschlagen"),
                ],
                default="CREATED",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.DeleteModel(
            name="MeetingParticipantChangeLog",
        ),
    ]
