# Generated by Django 6.0.4 on 2026-05-01

from django.db import migrations


def seed_participant_permissions(apps, schema_editor):
    """Create and assign participant permissions."""
    Permission = apps.get_model("roles", "Permission")
    Role = apps.get_model("roles", "Role")
    RolePermission = apps.get_model("roles", "RolePermission")

    permissions_data = [
        (
            "participant.view",
            "Teilnehmer anzeigen",
            "Sitzungsteilnehmer und Änderungsverlauf einsehen",
            "participant",
        ),
        (
            "participant.edit",
            "Teilnehmer bearbeiten",
            "Sitzungsteilnehmer für eine konkrete Sitzung bearbeiten",
            "participant",
        ),
        (
            "participant.mark_absent",
            "Teilnehmer abwesend setzen",
            "Abwesenheit und Nachladefähigkeit für Sitzungsteilnehmer erfassen",
            "participant",
        ),
        (
            "participant.manage_substitutes",
            "Ersatz verwalten",
            "Ersatzvorschläge prüfen und Ersatzteilnehmer bestätigen",
            "participant",
        ),
        (
            "participant.send_notifications",
            "Teilnehmer benachrichtigen",
            "Einladungs- und Nachlade-Mails an Sitzungsteilnehmer versenden",
            "participant",
        ),
    ]

    created_permissions = {}
    for codename, name, description, category in permissions_data:
        permission, created = Permission.objects.get_or_create(
            codename=codename,
            defaults={
                "name": name,
                "description": description,
                "category": category,
            },
        )
        created_permissions[codename] = permission

    role_permission_codes = {
        "SYSTEM_ADMIN": [permission[0] for permission in permissions_data],
        "CHAIR": [permission[0] for permission in permissions_data],
        "VICE_CHAIR": [permission[0] for permission in permissions_data],
        "CLERK": ["participant.view"],
        "MEMBER": ["participant.view"],
        "SUBSTITUTE": ["participant.view"],
        "EXTERNAL_MEMBER": ["participant.view"],
        "GUEST": ["participant.view"],
    }

    for role_codename, permission_codes in role_permission_codes.items():
        try:
            role = Role.objects.get(codename=role_codename)
        except Role.DoesNotExist:
            continue

        for permission_code in permission_codes:
            permission = created_permissions.get(permission_code)
            if permission:
                RolePermission.objects.get_or_create(
                    role=role,
                    permission=permission,
                )


def reverse_seed_participant_permissions(apps, schema_editor):
    """Remove participant permissions."""
    Permission = apps.get_model("roles", "Permission")
    RolePermission = apps.get_model("roles", "RolePermission")

    participant_permissions = Permission.objects.filter(category="participant")
    RolePermission.objects.filter(permission__in=participant_permissions).delete()
    participant_permissions.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("participants", "0001_initial"),
        ("roles", "9999_seed_roles_and_permissions"),
    ]

    operations = [
        migrations.RunPython(
            seed_participant_permissions,
            reverse_seed_participant_permissions,
        ),
    ]
