# Generated by Django 6.0.4 on 2026-05-08 11:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(max_length=64, verbose_name="Objekt-ID"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Erstellt"),
                            ("UPDATED", "Geändert"),
                            ("DELETED", "Gelöscht"),
                            ("FINALIZED", "Finalisiert"),
                            ("RECONFIRMED", "Erneut bestätigt"),
                        ],
                        max_length=30,
                        verbose_name="Aktion",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Geändert am"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(max_length=100, verbose_name="Änderungstyp"),
                ),
                (
                    "old_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Alter Stand"
                    ),
                ),
                (
                    "new_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Neuer Stand"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadaten"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Akteur",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_entries",
                        to="contenttypes.contenttype",
                        verbose_name="Objekttyp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit-Eintrag",
                "verbose_name_plural": "Audit-Einträge",
                "ordering": ["-changed_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_audit_content_e8ff27_idx",
                    ),
                    models.Index(
                        fields=["action", "changed_at"],
                        name="audit_audit_action_dd0700_idx",
                    ),
                ],
            },
        ),
    ]
