# Generated by Django 6.0.4 on 2026-04-27 11:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("committees", "0003_add_betriebsausschuss_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titel")),
                (
                    "meeting_number",
                    models.CharField(
                        help_text="Wird automatisch generiert (Format: YYYY-NN)",
                        max_length=20,
                        verbose_name="Sitzungsnummer",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                ("start_time", models.TimeField(verbose_name="Beginn")),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Geplantes Ende"
                    ),
                ),
                (
                    "actual_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Tatsächlicher Beginn"
                    ),
                ),
                (
                    "actual_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Tatsächliches Ende"
                    ),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online-Sitzung"),
                            ("HYBRID", "Hybrid-Sitzung"),
                            ("IN_PERSON", "Präsenzsitzung"),
                        ],
                        default="IN_PERSON",
                        max_length=10,
                        verbose_name="Sitzungstyp",
                    ),
                ),
                (
                    "location_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Online-Link"
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ortsbezeichnung"
                    ),
                ),
                (
                    "location_street",
                    models.CharField(blank=True, max_length=200, verbose_name="Straße"),
                ),
                (
                    "location_zip",
                    models.CharField(blank=True, max_length=10, verbose_name="PLZ"),
                ),
                (
                    "location_city",
                    models.CharField(blank=True, max_length=100, verbose_name="Stadt"),
                ),
                (
                    "location_room",
                    models.CharField(blank=True, max_length=100, verbose_name="Raum"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Entwurf"),
                            ("SENT", "Einladung versendet"),
                            ("IN_PROGRESS", "In Bearbeitung"),
                            ("COMPLETED", "Abgeschlossen"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_quorate",
                    models.BooleanField(
                        blank=True,
                        help_text="Wird nach Anwesenheitsprüfung automatisch gesetzt",
                        null=True,
                        verbose_name="Beschlussfähig",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Einladung versendet am"
                    ),
                ),
                (
                    "chair",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dynamische Auswahl aus allen aktiven Gremiumsmitgliedern",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chaired_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vorsitz",
                    ),
                ),
                (
                    "clerk",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dynamische Auswahl aus allen aktiven Gremiumsmitgliedern",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clerked_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Protokollführung",
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="committees.committee",
                        verbose_name="Gremium",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sitzung",
                "verbose_name_plural": "Sitzungen",
                "ordering": ["-date", "-start_time"],
                "indexes": [
                    models.Index(
                        fields=["committee", "date"],
                        name="meetings_me_committ_5226d7_idx",
                    ),
                    models.Index(
                        fields=["status"], name="meetings_me_status_14fbb6_idx"
                    ),
                    models.Index(
                        fields=["date", "start_time"],
                        name="meetings_me_date_231cba_idx",
                    ),
                ],
                "unique_together": {("committee", "meeting_number")},
            },
        ),
    ]
