# Generated by Django 6.0.4 on 2026-05-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "10000_meeting_current_agenda_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="actual_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Tatsächliches Abschlussdatum"
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="actual_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Tatsächliches Startdatum"
            ),
        ),
    ]
