# Generated by Django 6.0.4 on 2026-05-08 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendas", "10000_resolution_item_permissions"),
        ("meetings", "9999_seed_meeting_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="current_agenda_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_in_meetings",
                to="agendas.agendaitem",
                verbose_name="Aktueller Tagesordnungspunkt",
            ),
        ),
    ]
