# Generated by Django 6.0.4 on 2026-04-27 20:28

from django.db import migrations


def seed_meeting_permissions(apps, schema_editor):
    """Create and assign meeting permissions."""
    Permission = apps.get_model('roles', 'Permission')
    Role = apps.get_model('roles', 'Role')
    RolePermission = apps.get_model('roles', 'RolePermission')
    
    # Define all permissions
    permissions_data = [
        # Meeting permissions
        ('meeting.create', 'Sitzung erstellen (im eigenen Gremium)',
         'Sitzung im eigenen Gremium erstellen', 'meeting'),
        ('meeting.create_other', 'Sitzung in anderen Gremien erstellen',
         'Sitzung in beliebigen Gremien erstellen (nur Admins)', 'meeting'),
        ('meeting.view', 'Sitzung anzeigen',
         'Sitzungsdetails einsehen', 'meeting'),
        ('meeting.edit', 'Sitzung bearbeiten',
         'Sitzung bearbeiten (nur im Status DRAFT)', 'meeting'),
        ('meeting.delete_draft', 'Entwurf löschen',
         'Sitzungsentwurf löschen', 'meeting'),
        
        # Status workflow permissions
        ('meeting.send_invitation', 'Einladung versenden',
         'Status ändern: DRAFT → SENT (Einladung versenden)', 'meeting'),
        ('meeting.start_meeting', 'Sitzung beginnen',
         'Status ändern: SENT → IN_PROGRESS (Sitzung beginnen)', 'meeting'),
        ('meeting.complete_meeting', 'Sitzung abschließen',
         'Status ändern: IN_PROGRESS → COMPLETED (Sitzung abschließen)', 'meeting'),
        
        # Additional permissions
        ('meeting.manage_participants', 'Teilnehmer verwalten',
         'Teilnehmerliste verwalten', 'meeting'),
        ('meeting.lead_meeting', 'Sitzung leiten',
         'Sitzungsleitung übernehmen (verwendet für Default-Vorsitz)', 'meeting'),
        ('meeting.write_minutes', 'Protokoll schreiben',
         'Sitzungsprotokoll erstellen (verwendet für Default-Protokollführung)', 'meeting'),
        
        # Role eligibility permissions
        ('meeting.is_chair', 'Als Sitzungsleitung wählbar',
         'Person kann als Sitzungsleitung ausgewählt werden', 'meeting'),
        ('meeting.is_clerk', 'Als Schriftführung wählbar',
         'Person kann als Schriftführung ausgewählt werden', 'meeting'),
    ]
    
    # Create permissions
    created_permissions = {}
    for codename, name, description, category in permissions_data:
        permission, created = Permission.objects.get_or_create(
            codename=codename,
            defaults={
                'name': name,
                'description': description,
                'category': category
            }
        )
        created_permissions[codename] = permission
    
    # Assign all meeting permissions to SYSTEM_ADMIN
    try:
        system_admin = Role.objects.get(codename='SYSTEM_ADMIN')
        for permission in created_permissions.values():
            RolePermission.objects.get_or_create(
                role=system_admin,
                permission=permission
            )
    except Role.DoesNotExist:
        pass
    
    # Assign is_chair to chair roles
    chair_roles = ['CHAIR', 'VICE_CHAIR', 'VICE_CHAIR2']
    is_chair_perm = created_permissions.get('meeting.is_chair')
    if is_chair_perm:
        for role_code in chair_roles:
            try:
                role = Role.objects.get(codename=role_code)
                RolePermission.objects.get_or_create(
                    role=role,
                    permission=is_chair_perm
                )
            except Role.DoesNotExist:
                pass
    
    # Assign is_clerk to clerk role
    is_clerk_perm = created_permissions.get('meeting.is_clerk')
    if is_clerk_perm:
        try:
            clerk_role = Role.objects.get(codename='CLERK')
            RolePermission.objects.get_or_create(
                role=clerk_role,
                permission=is_clerk_perm
            )
        except Role.DoesNotExist:
            pass


def reverse_seed_permissions(apps, schema_editor):
    """Remove meeting permissions."""
    Permission = apps.get_model('roles', 'Permission')
    RolePermission = apps.get_model('roles', 'RolePermission')
    
    # Delete all RolePermissions for meeting permissions
    meeting_permissions = Permission.objects.filter(category='meeting')
    RolePermission.objects.filter(permission__in=meeting_permissions).delete()
    
    # Delete all meeting permissions
    meeting_permissions.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
        ("roles", "9999_seed_roles_and_permissions"),  # Ensure roles exist first
    ]

    operations = [
        migrations.RunPython(seed_meeting_permissions, reverse_seed_permissions),
    ]
