# Generated by Django 6.0.4 on 2026-04-27 20:28

from django.db import migrations


def seed_meeting_permissions(apps, schema_editor):
    """Create and assign meeting permissions."""
    Permission = apps.get_model('roles', 'Permission')
    Role = apps.get_model('roles', 'Role')
    RolePermission = apps.get_model('roles', 'RolePermission')
    
    # Define all permissions
    permissions_data = [
        # Meeting permissions
        ('meeting.create', 'Sitzung erstellen (im eigenen Gremium)',
         'Sitzung im eigenen Gremium erstellen', 'meeting'),
        ('meeting.create_other', 'Sitzung in anderen Gremien erstellen',
         'Sitzung in beliebigen Gremien erstellen (nur Admins)', 'meeting'),
        ('meeting.view', 'Sitzung anzeigen',
         'Sitzungsdetails einsehen', 'meeting'),
        ('meeting.edit', 'Sitzung bearbeiten',
         'Sitzung bearbeiten (nur im Status DRAFT)', 'meeting'),
        ('meeting.delete_draft', 'Entwurf löschen',
         'Sitzungsentwurf löschen', 'meeting'),
        
        # Status workflow permissions
        ('meeting.send_invitation', 'Einladung versenden',
         'Status ändern: DRAFT → SENT (Einladung versenden)', 'meeting'),
        ('meeting.start_meeting', 'Sitzung beginnen',
         'Status ändern: SENT → IN_PROGRESS (Sitzung beginnen)', 'meeting'),
        ('meeting.complete_meeting', 'Sitzung abschließen',
         'Status ändern: IN_PROGRESS → COMPLETED (Sitzung abschließen)', 'meeting'),
        
        # Role eligibility permissions
        ('meeting.is_chair', 'Als Sitzungsleitung wählbar',
         'Person kann als Sitzungsleitung ausgewählt werden', 'meeting'),
        ('meeting.is_clerk', 'Als Schriftführung wählbar',
         'Person kann als Schriftführung ausgewählt werden', 'meeting'),
    ]
    
    # Create permissions
    created_permissions = {}
    for codename, name, description, category in permissions_data:
        permission, created = Permission.objects.get_or_create(
            codename=codename,
            defaults={
                'name': name,
                'description': description,
                'category': category
            }
        )
        created_permissions[codename] = permission
    
    # Assign all meeting permissions to SYSTEM_ADMIN
    try:
        system_admin = Role.objects.get(codename='SYSTEM_ADMIN')
        for permission in created_permissions.values():
            RolePermission.objects.get_or_create(
                role=system_admin,
                permission=permission
            )
    except Role.DoesNotExist:
        pass
    
    # CHAIR gets: create, view, edit, delete_draft, send_invitation, start_meeting, 
    #             complete_meeting, is_chair
    try:
        chair = Role.objects.get(codename='CHAIR')
        chair_perm_codes = [
            'meeting.create', 'meeting.view', 'meeting.edit', 'meeting.delete_draft',
            'meeting.send_invitation', 'meeting.start_meeting', 'meeting.complete_meeting',
            'meeting.is_chair'
        ]
        for code in chair_perm_codes:
            perm = created_permissions.get(code)
            if perm:
                RolePermission.objects.get_or_create(
                    role=chair,
                    permission=perm
                )
    except Role.DoesNotExist:
        pass
    
    # VICE_CHAIR gets: create, view, edit, delete_draft, send_invitation, start_meeting,
    #                  complete_meeting, is_chair
    try:
        vice_chair = Role.objects.get(codename='VICE_CHAIR')
        vice_chair_perm_codes = [
            'meeting.create', 'meeting.view', 'meeting.edit', 'meeting.delete_draft',
            'meeting.send_invitation', 'meeting.start_meeting', 'meeting.complete_meeting',
            'meeting.is_chair'
        ]
        for code in vice_chair_perm_codes:
            perm = created_permissions.get(code)
            if perm:
                RolePermission.objects.get_or_create(
                    role=vice_chair,
                    permission=perm
                )
    except Role.DoesNotExist:
        pass
    
    # CLERK gets: create, view, delete_draft, is_clerk
    try:
        clerk = Role.objects.get(codename='CLERK')
        clerk_perm_codes = [
            'meeting.create', 'meeting.view', 'meeting.delete_draft',
            'meeting.is_clerk'
        ]
        for code in clerk_perm_codes:
            perm = created_permissions.get(code)
            if perm:
                RolePermission.objects.get_or_create(
                    role=clerk,
                    permission=perm
                )
    except Role.DoesNotExist:
        pass
    
    # MEMBER gets: view
    # Note: create, edit, delete_draft are conditional (only in Betriebsausschuss)
    # This will be handled by the permission checking logic in the views/services
    try:
        member = Role.objects.get(codename='MEMBER')
        member_perm_codes = ['meeting.view']
        for code in member_perm_codes:
            perm = created_permissions.get(code)
            if perm:
                RolePermission.objects.get_or_create(
                    role=member,
                    permission=perm
                )
    except Role.DoesNotExist:
        pass
    
    # EXTERNAL_MEMBER gets: view
    try:
        external_member = Role.objects.get(codename='EXTERNAL_MEMBER')
        external_perm = created_permissions.get('meeting.view')
        if external_perm:
            RolePermission.objects.get_or_create(
                role=external_member,
                permission=external_perm
            )
    except Role.DoesNotExist:
        pass
    
    # GUEST gets: view
    try:
        guest = Role.objects.get(codename='GUEST')
        guest_perm = created_permissions.get('meeting.view')
        if guest_perm:
            RolePermission.objects.get_or_create(
                role=guest,
                permission=guest_perm
            )
    except Role.DoesNotExist:
        pass


def reverse_seed_permissions(apps, schema_editor):
    """Remove meeting permissions."""
    Permission = apps.get_model('roles', 'Permission')
    RolePermission = apps.get_model('roles', 'RolePermission')
    
    # Delete all RolePermissions for meeting permissions
    meeting_permissions = Permission.objects.filter(category='meeting')
    RolePermission.objects.filter(permission__in=meeting_permissions).delete()
    
    # Delete all meeting permissions
    meeting_permissions.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
        ("roles", "9999_seed_roles_and_permissions"),  # Ensure roles exist first
    ]

    operations = [
        migrations.RunPython(seed_meeting_permissions, reverse_seed_permissions),
    ]
