# Generated by Django 6.0.4 on 2026-04-25 08:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        help_text='z.B. "meeting.create"',
                        max_length=100,
                        unique=True,
                        verbose_name="Code-Name",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "category",
                    models.CharField(
                        help_text='Modul/App (z.B. "meeting", "committee")',
                        max_length=50,
                        verbose_name="Kategorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Berechtigung",
                "verbose_name_plural": "Berechtigungen",
                "ordering": ["category", "codename"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "codename",
                    models.CharField(
                        help_text='z.B. "CHAIR", "SYSTEM_ADMIN"',
                        max_length=50,
                        unique=True,
                        verbose_name="Code-Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System-Rolle"),
                            ("COMMITTEE", "Gremiums-Rolle"),
                        ],
                        max_length=20,
                        verbose_name="Rollen-Typ",
                    ),
                ),
                (
                    "is_system_role",
                    models.BooleanField(
                        default=False,
                        help_text="Standard-Rollen können nicht gelöscht werden",
                        verbose_name="System-Rolle",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = System-generierte Rolle",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rolle",
                "verbose_name_plural": "Rollen",
                "ordering": ["role_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Zugewiesen am"
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Zugewiesen von",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roles.permission",
                        verbose_name="Berechtigung",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roles.role",
                        verbose_name="Rolle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rollen-Berechtigung",
                "verbose_name_plural": "Rollen-Berechtigungen",
                "ordering": ["role", "permission"],
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                related_name="roles",
                through="roles.RolePermission",
                to="roles.permission",
                verbose_name="Berechtigungen",
            ),
        ),
    ]
