# Generated by Django 6.0.4 on 2026-04-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Rolle",
                "verbose_name_plural": "Rollen",
            },
        ),
        migrations.AddField(
            model_name="role",
            name="sort_order",
            field=models.IntegerField(
                default=100,
                help_text="Niedrigere Werte = höhere Priorität (z.B. Vorsitz=1, Stellv.=2, etc.)",
                verbose_name="Sortierreihenfolge",
            ),
        ),
    ]
