# Generated by Django 6.0.4 on 2026-04-26 09:50

from django.db import migrations


def create_permissions(apps, schema_editor):
    """Create standard permissions for system and roles."""
    Permission = apps.get_model('roles', 'Permission')
    
    # Define all permissions as list of tuples
    # (codename, name, description, category)
    PERMISSIONS = [
        # System permissions
        ('system.admin', 'Systemweiter Admin-Zugriff', 
         'Voller Zugriff auf alle System-Funktionen', 'system'),
        ('system.manage_users', 'Benutzer verwalten',
         'Benutzer erstellen, bearbeiten und löschen', 'system'),
        
        # Role permissions
        ('role.create', 'Rolle erstellen',
         'Neue Rollen anlegen', 'role'),
        ('role.edit', 'Rolle bearbeiten',
         'Existierende Rollen bearbeiten', 'role'),
        ('role.delete', 'Rolle löschen',
         'Rollen löschen (außer System-Rollen)', 'role'),
        ('role.assign_permissions', 'Berechtigungen zuweisen',
         'Berechtigungen zu Rollen hinzufügen oder entfernen', 'role'),
        ('role.view', 'Rollen einsehen',
         'Liste aller Rollen anzeigen', 'role'),
        ('role.assign_to_member', 'Rolle zuweisen',
         'Rollen an Gremiumsmitglieder zuweisen', 'role'),
    ]
    
    for codename, name, description, category in PERMISSIONS:
        Permission.objects.get_or_create(
            codename=codename,
            defaults={
                'name': name,
                'description': description,
                'category': category
            }
        )


def reverse_permissions(apps, schema_editor):
    """Remove created permissions."""
    Permission = apps.get_model('roles', 'Permission')
    
    # Delete all permissions created by this migration
    Permission.objects.filter(
        codename__in=[
            'system.admin', 'system.manage_users',
            'role.create', 'role.edit', 'role.delete', 
            'role.assign_permissions', 'role.view', 'role.assign_to_member'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_role_options_role_sort_order'),
    ]

    operations = [
        migrations.RunPython(create_permissions, reverse_permissions),
    ]
