# Generated by Django 6.0.4 on 2026-04-26 09:50

from django.db import migrations


def create_roles(apps, schema_editor):
    """Create standard roles (system + committee) and assign permissions."""
    Role = apps.get_model('roles', 'Role')
    Permission = apps.get_model('roles', 'Permission')
    RolePermission = apps.get_model('roles', 'RolePermission')
    
    # Define system roles (codename, name, description, role_type, sort_order)
    SYSTEM_ROLES = [
        ('SYSTEM_ADMIN', 'System-Administrator', 
         'Vollständige System-Administration', 'SYSTEM', 1),
        ('USER', 'Benutzer', 
         'Standard-Benutzer ohne besondere Rechte', 'SYSTEM', 100),
    ]
    
    # Define committee roles (codename, name, description, role_type, sort_order)
    COMMITTEE_ROLES = [
        ('CHAIR', 'Vorsitz',
         'Vorsitzender des Gremiums', 'COMMITTEE', 1),
        ('VICE_CHAIR', 'Stellv. Vorsitz',
         'Stellvertretender Vorsitzender', 'COMMITTEE', 2),
        ('CLERK', 'Schriftführung',
         'Schriftführer des Gremiums', 'COMMITTEE', 3),
        ('MEMBER', 'Mitglied',
         'Reguläres Gremiumsmitglied', 'COMMITTEE', 10),
        ('SUBSTITUTE', 'Ersatzmitglied',
         'Ersatzmitglied für reguläre Mitglieder', 'COMMITTEE', 20),
        ('EXTERNAL_MEMBER', 'Externes Mitglied',
         'Externes Mitglied ohne Stimmrecht', 'COMMITTEE', 30),
        ('GUEST', 'Gast',
         'Gast ohne Stimmrecht', 'COMMITTEE', 40),
    ]
    
    # Create system roles
    for codename, name, description, role_type, sort_order in SYSTEM_ROLES:
        Role.objects.get_or_create(
            codename=codename,
            defaults={
                'name': name,
                'description': description,
                'role_type': role_type,
                'is_system_role': True,
                'sort_order': sort_order
            }
        )
    
    # Create committee roles
    for codename, name, description, role_type, sort_order in COMMITTEE_ROLES:
        Role.objects.get_or_create(
            codename=codename,
            defaults={
                'name': name,
                'description': description,
                'role_type': role_type,
                'is_system_role': True,
                'sort_order': sort_order
            }
        )
    
    # Assign ALL permissions to SYSTEM_ADMIN
    try:
        system_admin = Role.objects.get(codename='SYSTEM_ADMIN')
        all_perms = Permission.objects.all()
        
        for perm in all_perms:
            RolePermission.objects.get_or_create(
                role=system_admin,
                permission=perm
            )
    except Role.DoesNotExist:
        pass


def reverse_roles(apps, schema_editor):
    """Remove created roles."""
    Role = apps.get_model('roles', 'Role')
    
    # Delete all roles created by this migration
    Role.objects.filter(
        codename__in=[
            'SYSTEM_ADMIN', 'USER',
            'CHAIR', 'VICE_CHAIR', 'CLERK', 'MEMBER',
            'SUBSTITUTE', 'EXTERNAL_MEMBER', 'GUEST'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_seed_permissions'),
    ]

    operations = [
        migrations.RunPython(create_roles, reverse_roles),
    ]
