# Generated by Django 6.0.4 on 2026-04-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='auto_include_in_ba',
            field=models.BooleanField(default=False, help_text='Mitglieder mit dieser Rolle werden automatisch zum Betriebsausschuss hinzugefügt (§ 27 BetrVG)', verbose_name='Automatisch im Betriebsausschuss'),
        ),
    ]
