# Generated by Django 6.0.4 on 2026-04-26 11:02

from django.db import migrations


def set_auto_include_for_chairs(apps, schema_editor):
    """
    Set auto_include_in_ba=True for CHAIR and VICE_CHAIR roles.
    
    According to § 27 BetrVG, Betriebsausschuss must include:
    - Vorsitzende (Chair)
    - Stellvertreter (Vice-Chair)
    - Additional elected members
    """
    Role = apps.get_model('roles', 'Role')
    
    # Set auto_include_in_ba for CHAIR and VICE_CHAIR
    Role.objects.filter(
        codename__in=['CHAIR', 'VICE_CHAIR'],
        role_type='COMMITTEE'
    ).update(auto_include_in_ba=True)


def reverse_auto_include(apps, schema_editor):
    """Reverse the auto_include setting."""
    Role = apps.get_model('roles', 'Role')
    
    Role.objects.filter(
        codename__in=['CHAIR', 'VICE_CHAIR'],
        role_type='COMMITTEE'
    ).update(auto_include_in_ba=False)


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_add_auto_include_in_ba'),
    ]

    operations = [
        migrations.RunPython(set_auto_include_for_chairs, reverse_auto_include),
    ]
