# Generated by Django 6.0.4 on 2026-04-27 20:45

from django.db import migrations


def seed_roles_and_permissions(apps, schema_editor):
    """Create roles, permissions, and assign permissions to roles."""
    Role = apps.get_model('roles', 'Role')
    Permission = apps.get_model('roles', 'Permission')
    RolePermission = apps.get_model('roles', 'RolePermission')
    
    # ========== STEP 1: Create Permissions ==========
    
    # Define all permissions (codename, name, description, category)
    PERMISSIONS = [
        # System permissions
        ('system.admin', 'Systemweiter Admin-Zugriff', 
         'Voller Zugriff auf alle System-Funktionen', 'system'),
        ('system.manage_users', 'Benutzer verwalten',
         'Benutzer erstellen, bearbeiten und löschen', 'system'),
        
        # Role permissions
        ('role.create', 'Rolle erstellen',
         'Neue Rollen anlegen', 'role'),
        ('role.edit', 'Rolle bearbeiten',
         'Existierende Rollen bearbeiten', 'role'),
        ('role.delete', 'Rolle löschen',
         'Rollen löschen (außer System-Rollen)', 'role'),
        ('role.assign_permissions', 'Berechtigungen zuweisen',
         'Berechtigungen zu Rollen hinzufügen oder entfernen', 'role'),
        ('role.view', 'Rollen einsehen',
         'Liste aller Rollen anzeigen', 'role'),
        ('role.assign_to_member', 'Rolle zuweisen',
         'Rollen an Gremiumsmitglieder zuweisen', 'role'),
    ]
    
    for codename, name, description, category in PERMISSIONS:
        Permission.objects.get_or_create(
            codename=codename,
            defaults={
                'name': name,
                'description': description,
                'category': category
            }
        )
    
    # ========== STEP 2: Create Roles ==========
    
    # Define system roles (codename, name, description, role_type, sort_order)
    SYSTEM_ROLES = [
        ('SYSTEM_ADMIN', 'System-Administrator', 
         'Vollständige System-Administration', 'SYSTEM', 1),
        ('USER', 'Benutzer', 
         'Standard-Benutzer ohne besondere Rechte', 'SYSTEM', 100),
    ]
    
    # Define committee roles (codename, name, description, role_type, sort_order, auto_include_in_ba)
    COMMITTEE_ROLES = [
        ('CHAIR', 'Vorsitz',
         'Vorsitzender des Gremiums', 'COMMITTEE', 1, True),
        ('VICE_CHAIR', 'Stellv. Vorsitz',
         'Stellvertretender Vorsitzender', 'COMMITTEE', 2, True),
        ('VICE_CHAIR2', '2ter Stellv. Vorsitz',
         '2ter Stellvertretender Vorsitzender', 'COMMITTEE', 3, False),
        ('CLERK', 'Schriftführung',
         'Schriftführer des Gremiums', 'COMMITTEE', 4, False),
        ('MEMBER', 'Mitglied',
         'Reguläres Gremiumsmitglied', 'COMMITTEE', 10, False),
        ('SUBSTITUTE', 'Ersatzmitglied',
         'Ersatzmitglied für reguläre Mitglieder', 'COMMITTEE', 20, False),
        ('EXTERNAL_MEMBER', 'Externes Mitglied',
         'Externes Mitglied ohne Stimmrecht', 'COMMITTEE', 30, False),
        ('GUEST', 'Gast',
         'Gast ohne Stimmrecht', 'COMMITTEE', 40, False),
    ]
    
    # Create system roles
    for codename, name, description, role_type, sort_order in SYSTEM_ROLES:
        Role.objects.get_or_create(
            codename=codename,
            defaults={
                'name': name,
                'description': description,
                'role_type': role_type,
                'is_system_role': True,
                'sort_order': sort_order
            }
        )
    
    # Create committee roles
    for codename, name, description, role_type, sort_order, auto_include in COMMITTEE_ROLES:
        role, created = Role.objects.get_or_create(
            codename=codename,
            defaults={
                'name': name,
                'description': description,
                'role_type': role_type,
                'is_system_role': True,
                'sort_order': sort_order,
                'auto_include_in_ba': auto_include
            }
        )
        # Update auto_include_in_ba if role already existed
        if not created and role.auto_include_in_ba != auto_include:
            role.auto_include_in_ba = auto_include
            role.save()
    
    # ========== STEP 3: Assign ALL Permissions to SYSTEM_ADMIN ==========
    
    try:
        system_admin = Role.objects.get(codename='SYSTEM_ADMIN')
        all_perms = Permission.objects.all()
        
        for perm in all_perms:
            RolePermission.objects.get_or_create(
                role=system_admin,
                permission=perm
            )
    except Role.DoesNotExist:
        pass


def reverse_roles_and_permissions(apps, schema_editor):
    """Remove all roles and permissions created by this migration."""
    Role = apps.get_model('roles', 'Role')
    Permission = apps.get_model('roles', 'Permission')
    RolePermission = apps.get_model('roles', 'RolePermission')
    
    # Delete RolePermissions for these permissions
    system_role_perms = Permission.objects.filter(category__in=['system', 'role'])
    RolePermission.objects.filter(permission__in=system_role_perms).delete()
    
    # Delete permissions
    system_role_perms.delete()
    
    # Delete roles
    Role.objects.filter(
        codename__in=[
            'SYSTEM_ADMIN', 'USER',
            'CHAIR', 'VICE_CHAIR', 'VICE_CHAIR2', 'CLERK', 'MEMBER',
            'SUBSTITUTE', 'EXTERNAL_MEMBER', 'GUEST'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_add_auto_include_in_ba'),  # Requires auto_include_in_ba field
    ]

    operations = [
        migrations.RunPython(seed_roles_and_permissions, reverse_roles_and_permissions),
    ]
